### ISSUE TITLE
Error / improvement in config_example.json

### ISSUE THREAD

**Issue by Zodiac-69** [dalehumby/powermeter#1]
mqtt": {
    "server": "10.0.0.10",
    "username": null,
    "password": null
    }
Should be:

mqtt": {
    "server": "10.0.0.10",
    "username": "your-username",
    "password": "you-password"
    }

Might be obvious to some, newby like me it was not.

**Comment by dalehumby** [comment]
Hi @Zodiac-69 Thanks for the input, yes that wasn't very well explained, sorry about that.

I have added comments to [config_example.json](https://github.com/dalehumby/powermeter/blob/master/config_example.json) which should clarify for the next person.

I've also used the opportunity to add some images and a link to my DevFest video in which I go through MicroPython basics.

If you are on the home automation journey a possibly easier-to-maintain setup would be to use ESPHome, see the cookbook for [Non-Invasive Power Meter](https://esphome.io/cookbook/power_meter.html)

I'm going to mark this as closed, but if you need any other clarification please let me know.
